# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: action.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "action.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0c\x61\x63tion.proto\x12\x12\x61pp.schemas.action\x1a\x1fgoogle/protobuf/timestamp.proto"M\n\rActionContext\x12\x0c\n\x04seed\x18\x01 \x01(\x03\x12.\n\nupdated_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp"s\n\x0c\x41\x63tionCreate\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0c\n\x04tags\x18\x03 \x03(\t\x12\x32\n\x07\x63ontext\x18\x04 \x01(\x0b\x32!.app.schemas.action.ActionContext"\xaf\x01\n\x0c\x41\x63tionUpdate\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0c\n\x04tags\x18\x04 \x03(\t\x12\x32\n\x07\x63ontext\x18\x05 \x01(\x0b\x32!.app.schemas.action.ActionContext\x12.\n\ncreated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp"\xa9\x01\n\x06\x41\x63tion\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0c\n\x04tags\x18\x04 \x03(\t\x12\x32\n\x07\x63ontext\x18\x05 \x01(\x0b\x32!.app.schemas.action.ActionContext\x12.\n\ncreated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\x9f\x01\n\rActionService\x12\x46\n\x06\x43reate\x12 .app.schemas.action.ActionCreate\x1a\x1a.app.schemas.action.Action\x12\x46\n\x06Update\x12 .app.schemas.action.ActionUpdate\x1a\x1a.app.schemas.action.Actionb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "action_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_ACTIONCONTEXT"]._serialized_start = 69
    _globals["_ACTIONCONTEXT"]._serialized_end = 146
    _globals["_ACTIONCREATE"]._serialized_start = 148
    _globals["_ACTIONCREATE"]._serialized_end = 263
    _globals["_ACTIONUPDATE"]._serialized_start = 266
    _globals["_ACTIONUPDATE"]._serialized_end = 441
    _globals["_ACTION"]._serialized_start = 444
    _globals["_ACTION"]._serialized_end = 613
    _globals["_ACTIONSERVICE"]._serialized_start = 616
    _globals["_ACTIONSERVICE"]._serialized_end = 775
# @@protoc_insertion_point(module_scope)
